In [24]:
import sys
# Without following 2 lines, I cannot do something like EPData[EPData['uid']==0] 
# with a dataframe EPData
# See http://stackoverflow.com/questions/28983608/how-to-create-a-pandas-dataframe-containing-columns-with-special-characters  for further explanation
reload(sys)
sys.setdefaultencoding('utf-8') 
import pandas as pd
dataWithUserIDs = pd.read_csv("/Users/dharshid/CDIPS_Project/data/First100000_with_id.csv")

In [25]:
dataWithUserIDs.columns

Index([u'Unnamed: 0', u'Unnamed: 0.1', u'Unnamed: 0.1', u'gender',
       u'num_groups', u'num_entries', u'num_fans', u'num_friends', u'created',
       u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments', u'age', u'uid',
       u'certainty'],
      dtype='object')

In [26]:
dataWithUserIDs

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1 gender  num_groups  num_entries  \
0               0             0             0      F         210           54   
1               1             1             1      F          25            9   
2               2             3             3      M         153            2   
3               3             4             4      F          29            8   
4               4             5             5      M          14            1   
5               5             6             6      F        2993           62   
6               6             7             7      F          69           26   
7               7             8             8      M         250          255   
8               8             9             9      F          41           80   
9               9            10            10      M         263          104   
10             10            11            11      F         167           13   
11             11            12            12      M         304           25   
12             12            13            13      F          26           45   
13             13            14            14      F          26           14   
14             14            15            15      F         118          100   
15             15            16            16      F        1601           10   
16             16            17            17      M         401          429   
17             17            18            18      F         751            6   
18             18            19            19      M         426          458   
19             19            20            20      F         177           10   
20             20            21            21      F          58           17   
21             21            22            22      F          26           45   
22             22            23            23      F          87            8   
23             23            24            24      M         239           69   
24             24            25            25      F         140           13   
25             25            26            26      F         374          279   
26             26            27            27      F         247           22   
27             27            28            28      F           9            7   
28             28            29            29      M           7            1   
29             29            30            30      F         300           37   
...           ...           ...           ...    ...         ...          ...   
99970       99970        105765        105765      M          57           13   
99971       99971        105766        105766      M         357           72   
99972       99972        105767        105767      F          17            8   
99973       99973        105768        105768      M          29            8   
99974       99974        105769        105769      F          16           11   
99975       99975        105770        105770      M         847          294   
99976       99976        105771        105771      F         107           52   
99977       99977        105772        105772      M         700           53   
99978       99978        105773        105773      F         586          257   
99979       99979        105774        105774      F         605           88   
99980       99980        105775        105775      F        1259          416   
99981       99981        105776        105776      T         371          671   
99982       99982        105777        105777      M       29145        10881   
99983       99983        105778        105778      M          16          168   
99984       99984        105779        105779      M          11            1   
99985       99985        105780        105780      F         234           18   
99986       99986        105781        105781      F         571           81   
99987       99987        105782       

In [27]:
goodData = dataWithUserIDs[~(dataWithUserIDs['uid']==0)]

In [28]:
goodData = goodData[goodData['certainty']==True]

In [29]:
goodData

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1 gender  num_groups  num_entries  \
3               3             4             4      F          29            8   
4               4             5             5      M          14            1   
5               5             6             6      F        2993           62   
6               6             7             7      F          69           26   
8               8             9             9      F          41           80   
9               9            10            10      M         263          104   
10             10            11            11      F         167           13   
11             11            12            12      M         304           25   
12             12            13            13      F          26           45   
13             13            14            14      F          26           14   
14             14            15            15      F         118          100   
15             15            16            16      F        1601           10   
17             17            18            18      F         751            6   
19             19            20            20      F         177           10   
20             20            21            21      F          58           17   
21             21            22            22      F          26           45   
22             22            23            23      F          87            8   
23             23            24            24      M         239           69   
24             24            25            25      F         140           13   
25             25            26            26      F         374          279   
26             26            27            27      F         247           22   
27             27            28            28      F           9            7   
29             29            30            30      F         300           37   
30             30            31            31      M         239           61   
31             31            32            32      M         171          100   
32             32            33            33      F          75            9   
33             33            34            34      U         215          104   
35             35            36            36      M          72           92   
36             36            37            37      M          46           43   
38             38            39            39      M         446           23   
...           ...           ...           ...    ...         ...          ...   
99963       99963        105758        105758      F         155           84   
99964       99964        105759        105759      F         675           48   
99965       99965        105760        105760      M          86           13   
99966       99966        105761        105761      M          64           25   
99967       99967        105762        105762      U          31            9   
99968       99968        105763        105763      F         605           88   
99969       99969        105764        105764      F         134           11   
99970       99970        105765        105765      M          57           13   
99971       99971        105766        105766      M         357           72   
99974       99974        105769        105769      F          16           11   
99975       99975        105770        105770      M         847          294   
99976       99976        105771        105771      F         107           52   
99977       99977        105772        105772      M         700           53   
99979       99979        105774        105774      F         605           88   
99981       99981        105776        105776      T         371          671   
99982       99982        105777        105777      M       29145        10881   
99983       99983        105778        105778      M          16          168   
99985       99985        105780       

In [30]:
from numpy import loadtxt
top50Groups = loadtxt("/Users/dharshid/CDIPS_Project/data/top50groups.txt",comments="#",delimiter="\n",unpack=False)

In [39]:
top50Groups = top50Groups.astype(int)
top50Groups

array([  1728, 154884,  11525,   5382,    763,    233,    649, 974071,
        17036,  76430,   2108, 828259, 426065,    335,   8083,   2510,
         8726,   1431, 117528,     68,  23323,  42844,   2334,    887,
       102852, 646363,  43748,    165, 364326,   1009, 166260,    809,
         2475, 193494,   1261,   4527,   2534, 233190, 147547,   1843,
          984,  15349,    950,   5577,    332,  25529,  51387,   1340,
          109,   4603])

In [62]:
top50GroupData = goodData[goodData['gid']==top50Groups[0]]
top50GroupData = top50GroupData.append(goodData[goodData['gid']==top50Groups[1]],ignore_index=True)
top50GroupData

Unnamed: 0  Unnamed: 0.1  Unnamed: 0.1 gender  num_groups  num_entries  \
0           591           610           610      F          33           13   
1          1473          1577          1577      F          29           25   
2          3587          3819          3819      F          33           13   
3          4874          5186          5186      M         489          122   
4          5724          6101          6101      F        2492         1195   
5          5735          6113          6113      F        2492         1195   
6          6089          6484          6484      M         119           37   
7          6780          7224          7224      F         153           27   
8          6796          7241          7241      F         153           27   
9          6804          7250          7250      F         153           27   
10         6813          7260          7260      F         153           27   
11         6823          7271          7271      F         153           27   
12         6858          7312          7312      F         153           27   
13         6926          7389          7389      F        2492         1195   
14         7535          8040          8040      M        1365           42   
15         7776          8294          8294      M         416          104   
16         9164          9737          9737      F         113           18   
17        10470         11094         11094      F         146           47   
18        10487         11114         11114      M         431          121   
19        11147         11808         11808      F         599         1169   
20        12370         13108         13108      F        2492         1195   
21        13206         13976         13976      M         196           28   
22        18140         19175         19175      M          89           90   
23        19092         20179         20179      F         599         1169   
24        19565         20689         20689      M          62           10   
25        20052         21193         21193      T          38           27   
26        20331         21483         21483      M         503          127   
27        21608         22829         22829      T          38           27   
28        22186         23434         23434      M        1365           42   
29        22279         23532         23532      M        4030          147   
..          ...           ...           ...    ...         ...          ...   
80         2100          2226          2226      F         350           77   
81         2131          2259          2259      M          38           58   
82        11425         12099         12099      F         158           54   
83        20295         21447         21447      F         140           71   
84        21569         22786         22786      F         454          275   
85        23195         24497         24497      M         387          181   
86        23294         24599         24599      F        1850          755   
87        34853         36812         36812      F        2276         1070   
88        43090         45536         45536      F        1850          755   
89        43126         45574         45574      F         454          275   
90        43148         45596         45596      F        2276         1070   
91        50825         53793         53793      M         429          953   
92        52806         55880         55880      M         191          137   
93        53362         56454         56454      F        1850          755   
94        59617         63009         63009      M          45            2   
95        62330         65864         65864      F          36           41   
96        62983         66552         66552      M         113           42   
97        66648         70433         70433      F          26           44   
98        67603         71477         71477      F     

In [64]:
top50GroupData = goodData[goodData['gid']==top50Groups[0]]
for i in range(1,50):
    top50GroupData = top50GroupData.append(goodData[goodData['gid']==top50Groups[i]],ignore_index=True)

In [70]:
top50GroupData.columns

Index([u'Unnamed: 0', u'Unnamed: 0.1', u'Unnamed: 0.1', u'gender',
       u'num_groups', u'num_entries', u'num_fans', u'num_friends', u'created',
       u'last_login', u'num_logins', u'last_wall_activity',
       u'last_circle_activity', u'birthdate', u'gid', u'content',
       u'date_posted', u'votes', u'num_comments', u'age', u'uid',
       u'certainty'],
      dtype='object')

In [75]:
uidColNum = 20
gidColNum = 14
top50GroupData.iloc[1,[14,20]]

gid       1728
uid    8506518
Name: 1, dtype: object

In [74]:
top50GroupData.loc[1,['gid','uid']]

gid       1728
uid    8506518
Name: 1, dtype: object

In [77]:
import userGroupDict

In [81]:
top50GroupSorted = top50GroupData.sort(columns='uid')

In [93]:
topGroupSubset = top50GroupSorted.iloc[0:5000,:]
topGroupSubset.shape

(5000, 22)

In [94]:
userGroup = userGroupDict.makeUserGroupDict(topGroupSubset, uidColNum, gidColNum)

In [97]:
keyList = userGroup.keys()

In [98]:
keyList[0:5]

[1040397, 7790607, 6438929, 8142866, 4661267]

In [104]:
userGroup[keyList[4]]

{887: 1}

In [105]:
import numpy as np
zeroMatrix = np.zeros((2,3))

In [106]:
zeroMatrix

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [113]:
userSeries = topGroupSubset.iloc[0:20, 20]

In [114]:
userSeries

2951      47289
3133      47289
3239      47289
7538      54180
7359     318563
11214    477629
10031    488234
10030    488234
11102    493465
9383     500393
9666     500393
6270     500393
6271     500393
9714     500393
8692     500393
9115     500393
11136    572098
413      612408
2519     612408
11972    612408
Name: uid, dtype: int64

In [117]:
len(userSeries.unique())

9

In [118]:
x = np.random.randint(9, size=(3, 3))

In [119]:
x

array([[1, 2, 5],
       [8, 2, 0],
       [4, 3, 6]])

In [120]:
x[0,1] += 1

In [121]:
x

array([[1, 3, 5],
       [8, 2, 0],
       [4, 3, 6]])

In [122]:
top50Groups[0:7]

array([  1728, 154884,  11525,   5382,    763,    233,    649])

In [123]:
np.__version__

'1.9.2'

In [124]:
top50GroupData.shape

(12516, 22)

In [130]:
a = np.random.randint(9, size=(3,3))

In [131]:
a

array([[1, 1, 8],
       [4, 3, 8],
       [3, 7, 1]])

In [132]:
a[0,0] = 0
a[1,2] = 0
a[2,2] = 0
a[0,1] = 0

In [133]:
a

array([[0, 0, 8],
       [4, 3, 0],
       [3, 7, 0]])

In [138]:
nonzero = np.flatnonzero(a)
nonzero

array([2, 3, 4, 6, 7])

In [142]:
b = np.put(a, nonzero, 1)
a

array([[0, 0, 1],
       [1, 1, 0],
       [1, 1, 0]])

In [143]:
M = np.loadtxt("top50GroupsMatrix.txt")

In [144]:
M

array([[  0.,   0.,   0.,   1.,   0.,   0.,   0.],
       [  2.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   1.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   0.,   0.,   0.,   1.,   0.],
       [  0.,   1.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   1.,   0.,   0.,   0.,   0.],
       [  0.,   0.,  10.,   0.,   0.,   0.,   0.],
       [  0.,   0.,   2.,   0.,   0.,   0.,   0.]])

In [145]:
import turnToBinaryMatrix

In [146]:
M1 = turnToBinaryMatrix.turnToBinaryMatrix(M)

In [147]:
M1

array([[ 0.,  0.,  0.,  1.,  0.,  0.,  0.],
       [ 1.,  0.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  1.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.,  0.,  1.,  0.],
       [ 0.,  1.,  0.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.],
       [ 0.,  0.,  1.,  0.,  0.,  0.,  0.]])